/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NotificationPreferences = IDL.Record({
  'notificationsEnabled' : IDL.Bool,
  'notificationSound' : IDL.Text,
});
export const AdvancedSettings = IDL.Record({
  'hardwareAcceleration' : IDL.Bool,
  'proxySettings' : IDL.Text,
});
export const AppearanceSettings = IDL.Record({
  'theme' : IDL.Text,
  'fontSize' : IDL.Nat,
  'colorScheme' : IDL.Text,
});
export const BookmarkSettings = IDL.Record({
  'defaultBookmarkFolder' : IDL.Text,
  'bookmarksBarVisible' : IDL.Bool,
});
export const SearchPreferences = IDL.Record({
  'safeSearchEnabled' : IDL.Bool,
  'defaultSearchEngine' : IDL.Text,
});
export const PrivacySettings = IDL.Record({
  'doNotTrack' : IDL.Bool,
  'cookiePreferences' : IDL.Text,
});
export const Profile = IDL.Record({
  'notifications' : NotificationPreferences,
  'displayName' : IDL.Text,
  'advanced' : AdvancedSettings,
  'appearance' : AppearanceSettings,
  'bookmarks' : BookmarkSettings,
  'search' : SearchPreferences,
  'privacy' : PrivacySettings,
});

export const idlService = IDL.Service({
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getSettings' : IDL.Func([], [Profile], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'saveSettings' : IDL.Func([Profile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NotificationPreferences = IDL.Record({
    'notificationsEnabled' : IDL.Bool,
    'notificationSound' : IDL.Text,
  });
  const AdvancedSettings = IDL.Record({
    'hardwareAcceleration' : IDL.Bool,
    'proxySettings' : IDL.Text,
  });
  const AppearanceSettings = IDL.Record({
    'theme' : IDL.Text,
    'fontSize' : IDL.Nat,
    'colorScheme' : IDL.Text,
  });
  const BookmarkSettings = IDL.Record({
    'defaultBookmarkFolder' : IDL.Text,
    'bookmarksBarVisible' : IDL.Bool,
  });
  const SearchPreferences = IDL.Record({
    'safeSearchEnabled' : IDL.Bool,
    'defaultSearchEngine' : IDL.Text,
  });
  const PrivacySettings = IDL.Record({
    'doNotTrack' : IDL.Bool,
    'cookiePreferences' : IDL.Text,
  });
  const Profile = IDL.Record({
    'notifications' : NotificationPreferences,
    'displayName' : IDL.Text,
    'advanced' : AdvancedSettings,
    'appearance' : AppearanceSettings,
    'bookmarks' : BookmarkSettings,
    'search' : SearchPreferences,
    'privacy' : PrivacySettings,
  });
  
  return IDL.Service({
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getSettings' : IDL.Func([], [Profile], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'saveSettings' : IDL.Func([Profile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };