/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvancedSettings {
  'hardwareAcceleration' : boolean,
  'proxySettings' : string,
}
export interface AppearanceSettings {
  'theme' : string,
  'fontSize' : bigint,
  'colorScheme' : string,
}
export interface BookmarkSettings {
  'defaultBookmarkFolder' : string,
  'bookmarksBarVisible' : boolean,
}
export interface NotificationPreferences {
  'notificationsEnabled' : boolean,
  'notificationSound' : string,
}
export interface PrivacySettings {
  'doNotTrack' : boolean,
  'cookiePreferences' : string,
}
export interface Profile {
  'notifications' : NotificationPreferences,
  'displayName' : string,
  'advanced' : AdvancedSettings,
  'appearance' : AppearanceSettings,
  'bookmarks' : BookmarkSettings,
  'search' : SearchPreferences,
  'privacy' : PrivacySettings,
}
export interface SearchPreferences {
  'safeSearchEnabled' : boolean,
  'defaultSearchEngine' : string,
}
export interface _SERVICE {
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getSettings' : ActorMethod<[], Profile>,
  'isRegistered' : ActorMethod<[], boolean>,
  'saveSettings' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];